version: '3.9'

volumes:
  prometheus_data: {}

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "cscbase"
      POSTGRES_USER: "cscuser"
      POSTGRES_PASSWORD: "cscpass"
    ports:
      - "5433:5432"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  application:
    build:
      context: ..
      dockerfile: ./mts_grafana_sample/application/Dockerfile
    container_name: application
    env_file:
      - ./application/application.env
    ports:
      - "8095:8080"
    depends_on:
      - postgres