server.port: ${SERVER_PORT:8080}

spring.kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost:29092}
  consumer.group-id: burner_group

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: "ALWAYS"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

burner:
  clients: ${BURNER_CLIENTS:http://localhost:8080}