global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: mts_sample
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['application1:8080']
      - targets: ['application2:8080']
      - targets: ['application3:8080']
      - targets: ['burner:8080']

remote_write:
  - url: '<Your Prometheus remote_write endpoint>'
    basic_auth:
      username: '<Your Grafana Username>'
      password: '<Your Grafana API key>'